# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 200)
        MainWindow.setMinimumSize(QtCore.QSize(600, 200))
        MainWindow.setMaximumSize(QtCore.QSize(600, 200))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background: #7C7CD8")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_valida = QtWidgets.QLineEdit(self.centralwidget)
        self.input_valida.setGeometry(QtCore.QRect(130, 20, 330, 40))
        self.input_valida.setMinimumSize(QtCore.QSize(330, 40))
        self.input_valida.setMaximumSize(QtCore.QSize(330, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_valida.setFont(font)
        self.input_valida.setStyleSheet("background: white")
        self.input_valida.setObjectName("input_valida")
        self.btn_validar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_validar.setGeometry(QtCore.QRect(471, 24, 120, 35))
        self.btn_validar.setMinimumSize(QtCore.QSize(120, 35))
        self.btn_validar.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.btn_validar.setFont(font)
        self.btn_validar.setStyleSheet("background: #575793")
        self.btn_validar.setObjectName("btn_validar")
        self.btn_gerar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gerar.setGeometry(QtCore.QRect(471, 81, 120, 35))
        self.btn_gerar.setMinimumSize(QtCore.QSize(120, 35))
        self.btn_gerar.setMaximumSize(QtCore.QSize(120, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.btn_gerar.setFont(font)
        self.btn_gerar.setStyleSheet("background: #575793")
        self.btn_gerar.setObjectName("btn_gerar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("background: None")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 90, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: None")
        self.label_2.setObjectName("label_2")
        self.input_display = QtWidgets.QLineEdit(self.centralwidget)
        self.input_display.setEnabled(True)
        self.input_display.setGeometry(QtCore.QRect(20, 140, 550, 40))
        self.input_display.setMinimumSize(QtCore.QSize(550, 40))
        self.input_display.setMaximumSize(QtCore.QSize(550, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_display.setFont(font)
        self.input_display.setStyleSheet("color: None")
        self.input_display.setText("")
        self.input_display.setAlignment(QtCore.Qt.AlignCenter)
        self.input_display.setReadOnly(True)
        self.input_display.setObjectName("input_display")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CPF"))
        self.btn_validar.setText(_translate("MainWindow", "VALIDAR"))
        self.btn_gerar.setText(_translate("MainWindow", "GERAR"))
        self.label.setText(_translate("MainWindow", "Validar CPF:"))
        self.label_2.setText(_translate("MainWindow", "Gerar CPF:"))
